#!/usr/bin/env python

# Author : Chayapol Piyaphakdeesakun

import rospy
from sensor_msgs.msg import LaserScan, BatteryState
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry

valueLaser = [0.0]*360
valueLaserRaw = {
	'range_min':0.0,
	'range_max':0.0,
	'ranges':[0.0]*360,
	}
valueBatteryState = None
valueOdometry = {
	'position':{'x':0.0,'y':0.0,'z':0.0},
	'orientation':{'x':0.0,'y':0.0,'z':0.0,'w':1.0},
	'linearVelocity':{'x':0.0,'y':0.0,'z':0.0},
	'angularVelocity':{'x':0.0,'y':0.0,'z':0.0},
	}
cmd_vel_publisher = None
subscribers = []

def initRosNode():
	global cmd_vel_publisher
	global subscribers
	rospy.init_node('turtlebot3Controller',anonymous=True)
	rospy.on_shutdown(terminateRosNode)
	cmd_vel_publisher = rospy.Publisher('cmd_vel',Twist,queue_size=10)
	subscribers.append(rospy.Subscriber('scan',LaserScan,callback=scanSubscriberCallback))
	subscribers.append(rospy.Subscriber('battery_state',BatteryState,callback=batteryStateSubscriberCallback))
	subscribers.append(rospy.Subscriber('odom',Odometry,callback=odomSubscriberCallback))

def publishVelocityCommand(linearVelocity,angularVelocity):
	global cmd_vel_publisher
	twist = Twist()
	twist.linear.x = linearVelocity
	twist.angular.z = angularVelocity
	cmd_vel_publisher.publish(twist)

def sendOdometryReset():
	raise NotImplementedError()

def scanSubscriberCallback(message):
	global valueLaser
	global valueLaserRaw
	rawLaser = {
		'range_min':message.range_min,
		'range_max':message.range_max,
		'ranges':list(message.ranges),
		}
	laser = map(lambda x: x if x>message.range_min else message.range_min, message.ranges)
	laser = map(lambda x: x if x<message.range_max else message.range_max, laser)
	laser = list(laser)
	valueLaser = laser
	valueLaserRaw = rawLaser

def batteryStateSubscriberCallback(message):
	global valueBatteryState
	valueBatteryState = message

def odomSubscriberCallback(message):
	global valueOdometry
	valueOdometry = {
		'position':message.pose.pose.position,
		'orientation':message.pose.pose.orientation,
		'linearVelocity':message.twist.twist.linear,
		'angularVelocity':message.twist.twist.angular,
		}

def terminateRosNode():
	twist = Twist()
	twist.linear.x = 0.0
	twist.angular.z = 0.0
	pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
	pub.publish(twist)
	pub.unregister()
	global subscribers
	for sub in subscribers:
		sub.unregister()

def main():
	global valueLaser
	global valueLaserRaw
	global valueBatteryState
	global valueOdometry
	initRosNode()
	try:
		rate = rospy.Rate(10) #Control the rate of command send in unit of Hz
		while valueBatteryState ==None:
			pass
		batteryState = valueBatteryState	#copy sensor value before use
		print('BatteryVoltage: {}'.format(batteryState.voltage))
		##Write your robot control program here

		while not rospy.is_shutdown():
			try:
				rate.sleep()	#pause the program to maintain command rate
				publishVelocityCommand(0.00,0.05)
			except KeyboardInterrupt:
				terminateRosNode()
	except rospy.ROSInterruptException:
		pass
if __name__ == '__main__':
	main()
